### ISSUE TITLE
Minor typographical errors in the README.md

### ISSUE THREAD

**Issue by davidjstudholme** [JamesGallant/Genomics#4]
Just noticed a small typo:

"sudo run docker -v /home/user/path/to/myfiles:/home/pegasus/myfiles -it jamesgallant/pegasus" 

should actually  be:

"sudo docker run -v /home/user/path/to/myfiles:/home/pegasus/myfiles -it jamesgallant/pegasus"

Also, there seems to be some text missing from "be configured as well. Thi".

**Comment by JamesGallant** [comment]
Thanks! and I have fixed them

**Comment by davidjstudholme** [comment]
Thank you, James! I look forward to trying this out again later.

Best wishes,

David
